drive:
    freq_hertz: 20
    verbose: False
    verbosity: 20
parts:
 - led: 
      type: setup_GPIO
 - led: 
      type: sequential_LED_loop
      arguments:
        PIN_BLUE1: 26
        PIN_BLUE2: 19
        PIN_BLUE3: 13
        PIN_BLUE4: 6
 - joystick:
      type: PS3Controller
      arguments:
        scale_throttle_forward: 0.48
        scale_throttle_back: 1.1
        scale_steer_left: 1.0
        scale_steer_right: 1.0         
 - actuator:
        type: ThrottleController
        arguments:
          controller_select: PCA
          channel: 0
          full_reverse_pulse:     350
          full_forward_pulse:     400
          neutral_pulse:          370
 - actuator:
        type: SteeringController
        arguments:
          controller_select: PCA
          channel: 1
          full_left_pulse:    420
          full_right_pulse:   295
 - camera: 
        type: PiCam
 - datastore:
        type: WriteStore
        arguments:
            path: ~/mule_out
            flg_zip: 1
 - led:
      type: record_LED
      arguments: 
        PIN_RED: 16
         
